//! Anti-corruption layer (barrel adapter) generation.
//!
//! After a package is installed, fnpm can generate a barrel file under the
//! configured adapter directory. Application code then imports the package
//! through this single indirection point instead of importing it directly,
//! so a future package swap only requires changes in one file.

use anyhow::{anyhow, Result};
use std::fs;
use std::path::{Path, PathBuf};

/// Result of a barrel generation attempt.
#[derive(Debug, PartialEq, Eq)]
pub enum BarrelOutcome {
    /// A new barrel file was created at the given path.
    Created(PathBuf),
    /// A barrel file already existed at the given path; it was left untouched.
    AlreadyExists(PathBuf),
}

/// Strip a version/tag specifier from a package spec.
/// `axios@1.4.0` -> `axios`, `@scope/pkg@latest` -> `@scope/pkg`.
pub fn package_name_from_spec(spec: &str) -> &str {
    match spec.rfind('@') {
        Some(idx) if idx > 0 => &spec[..idx],
        _ => spec,
    }
}

/// Directory-safe name for a package: `@scope/pkg` -> `scope-pkg`.
fn adapter_dir_name(package_name: &str) -> String {
    package_name.trim_start_matches('@').replace('/', "-")
}

/// Heuristic: does the installed package expose a default export?
/// Reads the package's type declarations (or entry file as fallback) and
/// looks for `export default` / `export =` markers.
fn has_default_export(project_root: &Path, package_name: &str) -> bool {
    let pkg_dir = project_root.join("node_modules").join(package_name);
    let manifest_path = pkg_dir.join("package.json");

    let types_rel = fs::read_to_string(&manifest_path)
        .ok()
        .and_then(|content| serde_json::from_str::<serde_json::Value>(&content).ok())
        .and_then(|manifest| {
            ["types", "typings", "main"]
                .iter()
                .find_map(|key| manifest.get(key).and_then(|v| v.as_str().map(String::from)))
        })
        .unwrap_or_else(|| "index.d.ts".to_string());

    let mut candidates = vec![pkg_dir.join(&types_rel)];
    if !types_rel.ends_with(".d.ts") {
        candidates.push(pkg_dir.join(types_rel.replace(".js", ".d.ts")));
    }
    candidates.push(pkg_dir.join("index.d.ts"));

    candidates.iter().any(|path| {
        fs::read_to_string(path)
            .map(|content| content.contains("export default") || content.contains("export ="))
            .unwrap_or(false)
    })
}

/// Build the barrel file contents for a package.
fn barrel_contents(package_name: &str, with_default: bool) -> String {
    let default_line = if with_default {
        format!("export {{ default }} from '{package_name}';\n")
    } else {
        format!(
            "// If the package exposes a default export, uncomment the next line:\n// export {{ default }} from '{package_name}';\n"
        )
    };

    format!(
        "// Anti-corruption layer for '{package_name}' — generated by fnpm.\n\
         // Import from this module instead of '{package_name}' directly, so a future\n\
         // package swap only requires changes in this file.\n\
         \n\
         export * from '{package_name}';\n\
         {default_line}"
    )
}

/// Generate a barrel adapter for `package_spec` under `adapter_dir`
/// (relative to `project_root`). Uses `.ts` when a `tsconfig.json` exists
/// at the project root, `.js` otherwise. Never overwrites an existing barrel.
pub fn generate_barrel(
    project_root: &Path,
    adapter_dir: &str,
    package_spec: &str,
) -> Result<BarrelOutcome> {
    let package_name = package_name_from_spec(package_spec);
    if package_name.is_empty() {
        return Err(anyhow!("Empty package name in spec '{package_spec}'"));
    }

    let extension = if project_root.join("tsconfig.json").exists() {
        "ts"
    } else {
        "js"
    };

    let barrel_dir = project_root
        .join(adapter_dir)
        .join(adapter_dir_name(package_name));
    let barrel_path = barrel_dir.join(format!("index.{extension}"));

    if barrel_path.exists() {
        return Ok(BarrelOutcome::AlreadyExists(barrel_path));
    }

    fs::create_dir_all(&barrel_dir)?;
    let with_default = has_default_export(project_root, package_name);
    fs::write(&barrel_path, barrel_contents(package_name, with_default))?;

    Ok(BarrelOutcome::Created(barrel_path))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn fake_package(root: &Path, name: &str, dts_content: &str) {
        let pkg_dir = root.join("node_modules").join(name);
        fs::create_dir_all(&pkg_dir).unwrap();
        fs::write(
            pkg_dir.join("package.json"),
            format!(r#"{{"name": "{name}", "types": "index.d.ts"}}"#),
        )
        .unwrap();
        fs::write(pkg_dir.join("index.d.ts"), dts_content).unwrap();
    }

    #[test]
    fn test_package_name_from_spec() {
        assert_eq!(package_name_from_spec("axios"), "axios");
        assert_eq!(package_name_from_spec("axios@1.4.0"), "axios");
        assert_eq!(package_name_from_spec("@scope/pkg"), "@scope/pkg");
        assert_eq!(package_name_from_spec("@scope/pkg@latest"), "@scope/pkg");
    }

    #[test]
    fn test_adapter_dir_name() {
        assert_eq!(adapter_dir_name("axios"), "axios");
        assert_eq!(adapter_dir_name("@scope/pkg"), "scope-pkg");
    }

    #[test]
    fn test_generate_js_barrel_without_tsconfig() {
        let temp = TempDir::new().unwrap();
        let outcome = generate_barrel(temp.path(), "src/adapters", "axios").unwrap();

        let expected = temp.path().join("src/adapters/axios/index.js");
        assert_eq!(outcome, BarrelOutcome::Created(expected.clone()));

        let content = fs::read_to_string(expected).unwrap();
        assert!(content.contains("export * from 'axios';"));
        assert!(content.contains("// export { default } from 'axios';"));
    }

    #[test]
    fn test_generate_ts_barrel_with_tsconfig() {
        let temp = TempDir::new().unwrap();
        fs::write(temp.path().join("tsconfig.json"), "{}").unwrap();

        let outcome = generate_barrel(temp.path(), "src/adapters", "axios@1.4.0").unwrap();
        let expected = temp.path().join("src/adapters/axios/index.ts");
        assert_eq!(outcome, BarrelOutcome::Created(expected));
    }

    #[test]
    fn test_default_export_detected() {
        let temp = TempDir::new().unwrap();
        fake_package(
            temp.path(),
            "axios",
            "declare const axios: any;\nexport default axios;\n",
        );

        generate_barrel(temp.path(), "src/adapters", "axios").unwrap();
        let content = fs::read_to_string(temp.path().join("src/adapters/axios/index.js")).unwrap();
        assert!(content.contains("export { default } from 'axios';"));
        assert!(!content.contains("uncomment"));
    }

    #[test]
    fn test_scoped_package_barrel() {
        let temp = TempDir::new().unwrap();
        let outcome = generate_barrel(temp.path(), "src/adapters", "@scope/pkg@2.0.0").unwrap();

        let expected = temp.path().join("src/adapters/scope-pkg/index.js");
        assert_eq!(outcome, BarrelOutcome::Created(expected.clone()));

        let content = fs::read_to_string(expected).unwrap();
        assert!(content.contains("export * from '@scope/pkg';"));
    }

    #[test]
    fn test_existing_barrel_not_overwritten() {
        let temp = TempDir::new().unwrap();
        let barrel_dir = temp.path().join("src/adapters/axios");
        fs::create_dir_all(&barrel_dir).unwrap();
        fs::write(barrel_dir.join("index.js"), "// user-edited\n").unwrap();

        let outcome = generate_barrel(temp.path(), "src/adapters", "axios").unwrap();
        assert_eq!(
            outcome,
            BarrelOutcome::AlreadyExists(barrel_dir.join("index.js"))
        );

        let content = fs::read_to_string(barrel_dir.join("index.js")).unwrap();
        assert_eq!(content, "// user-edited\n");
    }

    #[test]
    fn test_empty_package_name_rejected() {
        let temp = TempDir::new().unwrap();
        assert!(generate_barrel(temp.path(), "src/adapters", "").is_err());
    }
}
