//! `fnpm adapt` — generate an anti-corruption layer (port + adapter) for an
//! installed package, inferred from how the project actually uses it.
//!
//! Unlike the barrel generated by `fnpm add --adapter` (a single re-export
//! point), `adapt` scans the project's own source code with the oxc AST,
//! collects the package members that are really used, and generates:
//!
//! - a **port**: an interface exposing only those members (TypeScript), and
//! - an **adapter**: an implementation of the port backed by the package.
//!
//! Application code can then depend on the port, keeping the package's API
//! and types from leaking across the codebase.

use anyhow::{anyhow, Result};
use oxc_allocator::Allocator;
use oxc_ast::ast::*;
use oxc_ast_visit::walk;
use oxc_ast_visit::Visit;
use oxc_parser::{Parser, ParserReturn};
use oxc_span::SourceType;
use std::collections::{BTreeSet, HashMap};
use std::fs;
use std::path::{Path, PathBuf};

use crate::adapter::package_name_from_spec;

/// How a local binding maps back to the package.
#[derive(Debug, Clone, PartialEq)]
enum BindingKind {
    /// `import axios from 'pkg'` or `const axios = require('pkg')`.
    Default,
    /// `import * as ns from 'pkg'` — members are named exports.
    Namespace,
}

/// Aggregated usage of a package across the project.
#[derive(Debug, Default)]
pub struct UsageReport {
    /// Members accessed on the default export (e.g. `axios.get`).
    pub default_members: BTreeSet<String>,
    /// Named exports imported or accessed via a namespace import.
    pub named_members: BTreeSet<String>,
    /// The default export itself is called as a function (e.g. `axios(...)`).
    pub default_called: bool,
    /// Files that import the package (relative paths).
    pub importing_files: Vec<PathBuf>,
    /// Total number of source files scanned.
    pub files_scanned: usize,
}

impl UsageReport {
    pub fn has_usage(&self) -> bool {
        !self.default_members.is_empty() || !self.named_members.is_empty() || self.default_called
    }
}

/// Per-file visitor that records which package members are used.
struct UsageVisitor<'a> {
    package: &'a str,
    /// Local binding name -> how it maps to the package.
    bindings: HashMap<String, BindingKind>,
    default_members: BTreeSet<String>,
    named_members: BTreeSet<String>,
    default_called: bool,
    imports_package: bool,
}

impl<'a> UsageVisitor<'a> {
    fn new(package: &'a str) -> Self {
        Self {
            package,
            bindings: HashMap::new(),
            default_members: BTreeSet::new(),
            named_members: BTreeSet::new(),
            default_called: false,
            imports_package: false,
        }
    }

    /// Is `expr` a `require('<package>')` call?
    fn is_require_of_package(&self, expr: &Expression<'a>) -> bool {
        if let Expression::CallExpression(call) = expr {
            if let Expression::Identifier(ident) = &call.callee {
                if ident.name == "require" && call.arguments.len() == 1 {
                    if let Some(Expression::StringLiteral(lit)) = call.arguments[0].as_expression()
                    {
                        return lit.value == self.package;
                    }
                }
            }
        }
        false
    }
}

impl<'a> Visit<'a> for UsageVisitor<'a> {
    fn visit_import_declaration(&mut self, decl: &ImportDeclaration<'a>) {
        if decl.source.value == self.package {
            self.imports_package = true;
            if let Some(specifiers) = &decl.specifiers {
                for spec in specifiers {
                    match spec {
                        ImportDeclarationSpecifier::ImportDefaultSpecifier(s) => {
                            self.bindings
                                .insert(s.local.name.to_string(), BindingKind::Default);
                        }
                        ImportDeclarationSpecifier::ImportNamespaceSpecifier(s) => {
                            self.bindings
                                .insert(s.local.name.to_string(), BindingKind::Namespace);
                        }
                        ImportDeclarationSpecifier::ImportSpecifier(s) => {
                            // A named import is part of the used surface by itself.
                            self.named_members.insert(s.imported.name().to_string());
                        }
                    }
                }
            }
        }
        walk::walk_import_declaration(self, decl);
    }

    fn visit_variable_declarator(&mut self, decl: &VariableDeclarator<'a>) {
        if let Some(init) = &decl.init {
            if self.is_require_of_package(init) {
                self.imports_package = true;
                match &decl.id {
                    // const axios = require('axios')
                    BindingPattern::BindingIdentifier(ident) => {
                        self.bindings
                            .insert(ident.name.to_string(), BindingKind::Default);
                    }
                    // const { get, post } = require('axios')
                    BindingPattern::ObjectPattern(pattern) => {
                        for prop in &pattern.properties {
                            if let Some(name) = prop.key.name() {
                                self.named_members.insert(name.into_owned());
                            }
                        }
                    }
                    _ => {}
                }
            }
        }
        walk::walk_variable_declarator(self, decl);
    }

    fn visit_member_expression(&mut self, expr: &MemberExpression<'a>) {
        if let MemberExpression::StaticMemberExpression(static_member) = expr {
            if let Expression::Identifier(ident) = &static_member.object {
                match self.bindings.get(ident.name.as_str()) {
                    Some(BindingKind::Default) => {
                        self.default_members
                            .insert(static_member.property.name.to_string());
                    }
                    Some(BindingKind::Namespace) => {
                        self.named_members
                            .insert(static_member.property.name.to_string());
                    }
                    None => {}
                }
            }
        }
        walk::walk_member_expression(self, expr);
    }

    fn visit_call_expression(&mut self, expr: &CallExpression<'a>) {
        // Direct call of the default binding: `axios(...)`.
        if let Expression::Identifier(ident) = &expr.callee {
            if self.bindings.get(ident.name.as_str()) == Some(&BindingKind::Default) {
                self.default_called = true;
            }
        }
        walk::walk_call_expression(self, expr);
    }
}

const SOURCE_EXTENSIONS: &[&str] = &["js", "jsx", "ts", "tsx", "mjs", "cjs", "mts", "cts"];
const SKIP_DIRS: &[&str] = &[
    "node_modules",
    ".git",
    "dist",
    "build",
    "out",
    "coverage",
    ".next",
    "target",
    ".fnpm",
];

/// Recursively collect source files under `root`, skipping vendored/build
/// directories and the adapter output directory itself (its adapter imports
/// the package and would otherwise count as usage on re-runs).
fn collect_source_files(root: &Path, adapter_root: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();

        if path.is_dir() {
            if SKIP_DIRS.contains(&name.as_str()) || path == adapter_root {
                continue;
            }
            collect_source_files(&path, adapter_root, out)?;
        } else if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
            if SOURCE_EXTENSIONS.contains(&ext) {
                out.push(path);
            }
        }
    }
    Ok(())
}

fn source_type_for(path: &Path) -> SourceType {
    let filepath = path.to_string_lossy();
    if filepath.ends_with(".ts") || filepath.ends_with(".mts") || filepath.ends_with(".cts") {
        SourceType::ts()
    } else if filepath.ends_with(".tsx") {
        SourceType::tsx()
    } else if filepath.ends_with(".jsx") {
        SourceType::jsx()
    } else if filepath.ends_with(".mjs") {
        SourceType::mjs()
    } else if filepath.ends_with(".cjs") {
        SourceType::cjs()
    } else {
        SourceType::unambiguous()
    }
}

/// Scan the project for usage of `package` and aggregate a report.
pub fn scan_usage(project_root: &Path, adapter_dir: &str, package: &str) -> Result<UsageReport> {
    let adapter_root = project_root.join(adapter_dir);
    let mut files = Vec::new();
    collect_source_files(project_root, &adapter_root, &mut files)?;

    let mut report = UsageReport {
        files_scanned: files.len(),
        ..Default::default()
    };

    for file in files {
        let Ok(source_text) = fs::read_to_string(&file) else {
            continue; // Non-UTF8 or unreadable: not a source file we can scan
        };

        let allocator = Allocator::default();
        let ParserReturn {
            program,
            diagnostics,
            ..
        } = Parser::new(&allocator, &source_text, source_type_for(&file)).parse();
        if diagnostics.has_errors() {
            continue; // Unparseable file: skip, same policy as the security scanner
        }

        let mut visitor = UsageVisitor::new(package);
        visitor.visit_program(&program);

        if visitor.imports_package {
            let relative = file
                .strip_prefix(project_root)
                .unwrap_or(&file)
                .to_path_buf();
            report.importing_files.push(relative);
        }
        report.default_members.extend(visitor.default_members);
        report.named_members.extend(visitor.named_members);
        report.default_called |= visitor.default_called;
    }

    Ok(report)
}

/// `@scope/pkg` -> `ScopePkg`, `left-pad` -> `LeftPad`.
fn pascal_case(package_name: &str) -> String {
    package_name
        .split(|c: char| !c.is_alphanumeric())
        .filter(|s| !s.is_empty())
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel_case(package_name: &str) -> String {
    let pascal = pascal_case(package_name);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// Directory-safe name, mirroring the barrel convention: `@scope/pkg` -> `scope-pkg`.
fn dir_name(package_name: &str) -> String {
    package_name.trim_start_matches('@').replace('/', "-")
}

/// Files generated by [`generate_port_and_adapter`].
#[derive(Debug)]
pub struct GeneratedLayer {
    pub port_path: Option<PathBuf>,
    pub adapter_path: PathBuf,
    pub index_path: PathBuf,
}

fn port_contents(package_name: &str, port_name: &str, report: &UsageReport) -> String {
    let mut imports = String::new();
    if !report.default_members.is_empty() || report.default_called {
        imports.push_str(&format!("import type _default from '{package_name}';\n"));
    }
    if !report.named_members.is_empty() {
        imports.push_str(&format!("import type * as _pkg from '{package_name}';\n"));
    }

    let mut members = String::new();
    if report.default_called {
        members.push_str(
            "  // Your code calls the package directly as a function.\n  call: typeof _default;\n",
        );
    }
    for member in &report.default_members {
        members.push_str(&format!("  {member}: typeof _default.{member};\n"));
    }
    for member in &report.named_members {
        members.push_str(&format!("  {member}: typeof _pkg.{member};\n"));
    }

    format!(
        "// Port over '{package_name}' — generated by fnpm from actual usage.\n\
         // Only the members your code uses today. Reshape it toward your domain\n\
         // (rename members, replace package types with your own) — the goal is\n\
         // that nothing outside this directory imports '{package_name}'.\n\
         \n\
         {imports}\
         \n\
         export interface {port_name} {{\n\
         {members}\
         }}\n"
    )
}

fn adapter_contents_ts(
    package_name: &str,
    port_name: &str,
    adapter_name: &str,
    port_module: &str,
    report: &UsageReport,
) -> String {
    let mut imports = String::new();
    if !report.default_members.is_empty() || report.default_called {
        imports.push_str(&format!("import _default from '{package_name}';\n"));
    }
    if !report.named_members.is_empty() {
        imports.push_str(&format!("import * as _pkg from '{package_name}';\n"));
    }
    imports.push_str(&format!(
        "import type {{ {port_name} }} from './{port_module}.js';\n"
    ));

    let mut members = String::new();
    if report.default_called {
        members.push_str("  call: _default,\n");
    }
    for member in &report.default_members {
        members.push_str(&format!("  {member}: _default.{member}.bind(_default),\n"));
    }
    for member in &report.named_members {
        members.push_str(&format!("  {member}: _pkg.{member},\n"));
    }

    format!(
        "// Adapter implementing the port with '{package_name}'.\n\
         // Swapping the package later = writing a new adapter for the same port.\n\
         \n\
         {imports}\
         \n\
         export const {adapter_name}: {port_name} = {{\n\
         {members}\
         }};\n"
    )
}

fn adapter_contents_js(package_name: &str, adapter_name: &str, report: &UsageReport) -> String {
    let mut imports = String::new();
    if !report.default_members.is_empty() || report.default_called {
        imports.push_str(&format!("import _default from '{package_name}';\n"));
    }
    if !report.named_members.is_empty() {
        imports.push_str(&format!("import * as _pkg from '{package_name}';\n"));
    }

    let mut members = String::new();
    if report.default_called {
        members.push_str("  call: _default,\n");
    }
    for member in &report.default_members {
        members.push_str(&format!("  {member}: _default.{member}.bind(_default),\n"));
    }
    for member in &report.named_members {
        members.push_str(&format!("  {member}: _pkg.{member},\n"));
    }

    format!(
        "// Adapter over '{package_name}' — generated by fnpm from actual usage.\n\
         // Import this object instead of '{package_name}' so a future package\n\
         // swap only requires rewriting this file.\n\
         \n\
         {imports}\
         \n\
         export const {adapter_name} = {{\n\
         {members}\
         }};\n"
    )
}

/// Generate the port + adapter files for `package_spec` from a usage report.
/// TypeScript projects (with `tsconfig.json`) get a typed port interface;
/// JavaScript projects get an adapter object only. Never overwrites files.
pub fn generate_port_and_adapter(
    project_root: &Path,
    adapter_dir: &str,
    package_spec: &str,
    report: &UsageReport,
) -> Result<GeneratedLayer> {
    let package_name = package_name_from_spec(package_spec);
    if package_name.is_empty() {
        return Err(anyhow!("Empty package name in spec '{package_spec}'"));
    }
    if !report.has_usage() {
        return Err(anyhow!(
            "No usage of '{package_name}' found in project sources"
        ));
    }

    let is_ts = project_root.join("tsconfig.json").exists();
    let dir = dir_name(package_name);
    let out_dir = project_root.join(adapter_dir).join(&dir);
    fs::create_dir_all(&out_dir)?;

    let port_name = format!("{}Port", pascal_case(package_name));
    let adapter_name = format!("{}Adapter", camel_case(package_name));
    let port_module = format!("{dir}.port");

    let write_new = |path: &Path, contents: String| -> Result<()> {
        if path.exists() {
            return Err(anyhow!(
                "{} already exists — refusing to overwrite. Delete it first to regenerate.",
                path.display()
            ));
        }
        fs::write(path, contents)?;
        Ok(())
    };

    if is_ts {
        let port_path = out_dir.join(format!("{port_module}.ts"));
        let adapter_path = out_dir.join(format!("{dir}.adapter.ts"));
        let index_path = out_dir.join("index.ts");

        write_new(&port_path, port_contents(package_name, &port_name, report))?;
        write_new(
            &adapter_path,
            adapter_contents_ts(
                package_name,
                &port_name,
                &adapter_name,
                &port_module,
                report,
            ),
        )?;
        write_new(
            &index_path,
            format!(
                "export type {{ {port_name} }} from './{port_module}.js';\nexport {{ {adapter_name} }} from './{dir}.adapter.js';\n"
            ),
        )?;

        Ok(GeneratedLayer {
            port_path: Some(port_path),
            adapter_path,
            index_path,
        })
    } else {
        let adapter_path = out_dir.join(format!("{dir}.adapter.js"));
        let index_path = out_dir.join("index.js");

        write_new(
            &adapter_path,
            adapter_contents_js(package_name, &adapter_name, report),
        )?;
        write_new(
            &index_path,
            format!("export {{ {adapter_name} }} from './{dir}.adapter.js';\n"),
        )?;

        Ok(GeneratedLayer {
            port_path: None,
            adapter_path,
            index_path,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write_source(root: &Path, rel: &str, content: &str) {
        let path = root.join(rel);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    #[test]
    fn test_scan_default_import_members() {
        let temp = TempDir::new().unwrap();
        write_source(
            temp.path(),
            "src/api.ts",
            "import axios from 'axios';\n\
             export const fetchUser = (id: string) => axios.get(`/users/${id}`);\n\
             export const saveUser = (u: object) => axios.post('/users', u);\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "axios").unwrap();
        assert_eq!(
            report.default_members,
            BTreeSet::from(["get".to_string(), "post".to_string()])
        );
        assert!(!report.default_called);
        assert_eq!(report.importing_files.len(), 1);
    }

    #[test]
    fn test_scan_named_and_namespace_imports() {
        let temp = TempDir::new().unwrap();
        write_source(
            temp.path(),
            "src/a.ts",
            "import { debounce } from 'lodash';\ndebounce(() => {}, 100);\n",
        );
        write_source(
            temp.path(),
            "src/b.ts",
            "import * as _ from 'lodash';\n_.throttle(() => {}, 100);\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "lodash").unwrap();
        assert_eq!(
            report.named_members,
            BTreeSet::from(["debounce".to_string(), "throttle".to_string()])
        );
        assert!(report.default_members.is_empty());
    }

    #[test]
    fn test_scan_require_patterns() {
        let temp = TempDir::new().unwrap();
        write_source(
            temp.path(),
            "src/legacy.cjs",
            "const axios = require('axios');\n\
             const { isAxiosError } = require('axios');\n\
             axios.get('/x');\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "axios").unwrap();
        assert_eq!(report.default_members, BTreeSet::from(["get".to_string()]));
        assert_eq!(
            report.named_members,
            BTreeSet::from(["isAxiosError".to_string()])
        );
    }

    #[test]
    fn test_scan_direct_default_call() {
        let temp = TempDir::new().unwrap();
        write_source(
            temp.path(),
            "src/api.ts",
            "import axios from 'axios';\naxios({ url: '/x' });\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "axios").unwrap();
        assert!(report.default_called);
    }

    #[test]
    fn test_scan_ignores_other_packages_and_skip_dirs() {
        let temp = TempDir::new().unwrap();
        write_source(
            temp.path(),
            "src/a.ts",
            "import axios from 'axios';\naxios.get('/x');\n",
        );
        write_source(
            temp.path(),
            "src/b.ts",
            "import fetch from 'node-fetch';\nfetch.default('/y');\n",
        );
        write_source(
            temp.path(),
            "node_modules/evil/index.js",
            "import axios from 'axios';\naxios.delete('/z');\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "axios").unwrap();
        assert_eq!(report.default_members, BTreeSet::from(["get".to_string()]));
    }

    #[test]
    fn test_scan_skips_existing_adapter_dir() {
        let temp = TempDir::new().unwrap();
        write_source(
            temp.path(),
            "src/adapters/axios/axios.adapter.ts",
            "import _default from 'axios';\nexport const a = { del: _default.delete };\n",
        );
        write_source(
            temp.path(),
            "src/api.ts",
            "import axios from 'axios';\naxios.get('/x');\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "axios").unwrap();
        assert_eq!(report.default_members, BTreeSet::from(["get".to_string()]));
    }

    #[test]
    fn test_generate_ts_layer() {
        let temp = TempDir::new().unwrap();
        fs::write(temp.path().join("tsconfig.json"), "{}").unwrap();
        write_source(
            temp.path(),
            "src/api.ts",
            "import axios from 'axios';\n\
             import { isAxiosError } from 'axios';\n\
             axios.get('/x');\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "axios").unwrap();
        let layer =
            generate_port_and_adapter(temp.path(), "src/adapters", "axios", &report).unwrap();

        let port = fs::read_to_string(layer.port_path.unwrap()).unwrap();
        assert!(port.contains("export interface AxiosPort"));
        assert!(port.contains("get: typeof _default.get;"));
        assert!(port.contains("isAxiosError: typeof _pkg.isAxiosError;"));

        let adapter = fs::read_to_string(&layer.adapter_path).unwrap();
        assert!(adapter.contains("export const axiosAdapter: AxiosPort"));
        assert!(adapter.contains("get: _default.get.bind(_default),"));
        assert!(adapter.contains("isAxiosError: _pkg.isAxiosError,"));

        let index = fs::read_to_string(&layer.index_path).unwrap();
        assert!(index.contains("export type { AxiosPort }"));
        assert!(index.contains("export { axiosAdapter }"));
    }

    #[test]
    fn test_generate_js_layer() {
        let temp = TempDir::new().unwrap();
        write_source(
            temp.path(),
            "src/api.js",
            "import axios from 'axios';\naxios.get('/x');\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "axios").unwrap();
        let layer =
            generate_port_and_adapter(temp.path(), "src/adapters", "axios", &report).unwrap();

        assert!(layer.port_path.is_none());
        let adapter = fs::read_to_string(&layer.adapter_path).unwrap();
        assert!(adapter.contains("export const axiosAdapter = {"));
        assert!(adapter.contains("get: _default.get.bind(_default),"));
    }

    #[test]
    fn test_generate_scoped_package_names() {
        let temp = TempDir::new().unwrap();
        fs::write(temp.path().join("tsconfig.json"), "{}").unwrap();
        write_source(
            temp.path(),
            "src/a.ts",
            "import slugify from '@sindresorhus/slugify';\nslugify('x');\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "@sindresorhus/slugify").unwrap();
        assert!(report.default_called);

        let layer = generate_port_and_adapter(
            temp.path(),
            "src/adapters",
            "@sindresorhus/slugify",
            &report,
        )
        .unwrap();
        let port = fs::read_to_string(layer.port_path.unwrap()).unwrap();
        assert!(port.contains("export interface SindresorhusSlugifyPort"));
        assert!(port.contains("call: typeof _default;"));
    }

    #[test]
    fn test_generate_refuses_overwrite() {
        let temp = TempDir::new().unwrap();
        write_source(
            temp.path(),
            "src/api.js",
            "import axios from 'axios';\naxios.get('/x');\n",
        );
        write_source(
            temp.path(),
            "src/adapters/axios/axios.adapter.js",
            "// mine\n",
        );

        let report = scan_usage(temp.path(), "src/adapters", "axios").unwrap();
        let result = generate_port_and_adapter(temp.path(), "src/adapters", "axios", &report);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("already exists"));
    }

    #[test]
    fn test_no_usage_is_error() {
        let temp = TempDir::new().unwrap();
        let report = scan_usage(temp.path(), "src/adapters", "axios").unwrap();
        assert!(!report.has_usage());
        assert!(generate_port_and_adapter(temp.path(), "src/adapters", "axios", &report).is_err());
    }

    #[test]
    fn test_case_helpers() {
        assert_eq!(pascal_case("axios"), "Axios");
        assert_eq!(pascal_case("left-pad"), "LeftPad");
        assert_eq!(pascal_case("@sindresorhus/slugify"), "SindresorhusSlugify");
        assert_eq!(camel_case("left-pad"), "leftPad");
    }
}
